# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_hellonbdev.ipynb"}

modules = ["hellonbdev.py"]

doc_url = "https://XinhaoLi74.github.io/molds/"

git_url = "https://github.com/XinhaoLi74/molds/tree/master/"

def custom_doc_links(name): return None
