# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"remove_mixture": "00_MolStandardizer.ipynb",
         "MolStandardizer": "00_MolStandardizer.ipynb",
         "DSclearner": "00_MolStandardizer.ipynb",
         "generate_scaffold": "01_DSsplitter.ipynb",
         "scaffold_to_smiles": "01_DSsplitter.ipynb",
         "scaffold_split": "01_DSsplitter.ipynb",
         "random_split": "01_DSsplitter.ipynb",
         "generate_folds": "01_DSsplitter.ipynb"}

modules = ["MolStandardizer.py",
           "DSsplitter.py"]

doc_url = "https://XinhaoLi74.github.io/molds/"

git_url = "https://github.com/XinhaoLi74/molds/tree/master/"

def custom_doc_links(name): return None
